[package]
name = "httpauvre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
env_logger = "0.10.0"
log = "0.4.19"
open = "4.1.0"
tokio = { version = "1", features = ["full"] }

